TravelEurope/Areas/AdminPanel/Controllers/VozilaController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TravelEurope.Data;
using TravelEurope.Areas.AdminPanel.ViewModels;
using TravelEurope.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace TravelEurope.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Area("AdminPanel")]
    public class VozilaController : Controller
    {
        private ApplicationDbContext _context;

        public VozilaController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            VozilaIndexVM vm = new VozilaIndexVM()
            {
                Rows = _context.Vozilo.Select(x => new VozilaIndexVM.Row()
                {
                    VoziloId = x.VoziloId,
                    Naziv = x.Naziv,
                    TipVozila = x.TipVozila.Naziv,
                    GodinaProizvodnje = x.GodinaProizvodnje,
                    MarkaVozila = x.MarkaVozila.Naziv,
                    BrojSjedista = x.BrojSjedista,
                    Boja = x.Boja,
                    BrojVrata = x.BrojVrata,
                    StatusVozila = x.StatusVozila.Status,
                    VrstaGoriva = x.VrstaGoriva.Naziv,
                    CijenaPoDanu = x.CijenaPoDanu,
                }).ToList()
            };
            return View(vm);
        }
    }
}

TravelEurope/Areas/RadnikPanel/Controllers/VozilaController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TravelEurope.Data;
using TravelEurope.Areas.RadnikPanel.ViewModels;
using TravelEurope.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace TravelEurope.Areas.RadnikPanel.Controllers
{
    [Authorize(Roles = "Radnik")]
    [Area("RadnikPanel")]
    public class VozilaController : Controller
    {
        private ApplicationDbContext _context;

        public VozilaController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            VozilaIndexVM vm = new VozilaIndexVM()
            {
                Rows = _context.Vozilo.Select(x => new VozilaIndexVM.Row()
                {
                    VoziloId = x.VoziloId,
                    Naziv = x.Naziv,
                    TipVozila = x.TipVozila.Naziv,
                    GodinaProizvodnje = x.GodinaProizvodnje,
                    MarkaVozila = x.MarkaVozila.Naziv,
                    BrojSjedista = x.BrojSjedista,
                    Boja = x.Boja,
                    BrojVrata = x.BrojVrata,
                    StatusVozila = x.StatusVozila.Status,
                    VrstaGoriva = x.VrstaGoriva.Naziv,
                    CijenaPoDanu = x.CijenaPoDanu,
                }).ToList()
            };
            return View(vm);
        }

        public IActionResult Dodaj()
        {
            VozilaDodajVM vm = new VozilaDodajVM()
            {
                TipVozilaLista = _context.TipVozila.Select(x => new SelectListItem
                {
                    Value = x.TipId.ToString(),
                    Text = x.Naziv
                }).ToList(),
                MarkaVozilaLista = _context.MarkaVozila.Select(x => new SelectListItem
                {
                    Value = x.MarkaId.ToString(),
                    Text = x.Naziv
                }).ToList(),
                StatusVozilaLista = _context.StatusVozila.Select(x => new SelectListItem
                {
                    Value = x.StatusVozilaId.ToString(),
                    Text = x.Status
                }).ToList(),
                VrstaGorivaLista = _context.VrstaGoriva.Select(x => new SelectListItem
                {
                    Value = x.GorivoId.ToString(),
                    Text = x.Naziv
                }).ToList(),
            };
            return PartialView(vm);
        }

        [HttpPost]
        public IActionResult Dodaj(VozilaDodajVM vm)
        {
            Vozilo v = _context.Vozilo.Where(a => a.VoziloId == vm.VoziloId).SingleOrDefault();
            if (v == null)
            {
                Vozilo a = new Vozilo
                {
                    VoziloId = vm.VoziloId,
                    Naziv = vm.Naziv,
                    MarkaVozilaId = vm.MarkaVozilaId,
                    GodinaProizvodnje = vm.GodinaProizvodnje,
                    TipVozilaId = vm.TipVozilaId,
                    StatusVozilaId = vm.StatusVozilaId,
                    VrstaGorivaId = vm.VrstaGorivaId,
                    BrojSjedista = vm.BrojSjedista,
                    Boja = vm.Boja,
                    BrojVrata = vm.BrojVrata,
                    CijenaPoDanu = vm.CijenaPoDanu
                };

                _context.Vozilo.Add(a);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            v.VoziloId = vm.VoziloId;
            v.Naziv = vm.Naziv;
            v.MarkaVozilaId = vm.MarkaVozilaId;
            v.GodinaProizvodnje = vm.GodinaProizvodnje;
            v.TipVozilaId = vm.TipVozilaId;
            v.StatusVozilaId = vm.StatusVozilaId;
            v.VrstaGorivaId = vm.VrstaGorivaId;
            v.BrojSjedista = vm.BrojSjedista;
            v.Boja = vm.Boja;
            v.BrojVrata = vm.BrojVrata;
            v.CijenaPoDanu = vm.CijenaPoDanu;

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Uredi(int id)
        {
            VozilaDodajVM vm = new VozilaDodajVM();
            Vozilo v = _context.Vozilo.Where(a => a.VoziloId == id).SingleOrDefault();

            vm.TipVozilaLista = _context.TipVozila.Select(x => new SelectListItem
            {
                Value = x.TipId.ToString(),
                Text = x.Naziv
            }).ToList();
            vm.MarkaVozilaLista = _context.MarkaVozila.Select(x => new SelectListItem
            {
                Value = x.MarkaId.ToString(),
                Text = x.Naziv
            }).ToList();
            vm.StatusVozilaLista = _context.StatusVozila.Select(x => new SelectListItem
            {
                Value = x.StatusVozilaId.ToString(),
                Text = x.Status
            }).ToList();
            vm.VrstaGorivaLista = _context.VrstaGoriva.Select(x => new SelectListItem
            {
                Value = x.GorivoId.ToString(),
                Text = x.Naziv
            }).ToList();

            vm.VoziloId = id;
            vm.Naziv = v.Naziv;
            vm.MarkaVozilaId = v.MarkaVozilaId;
            vm.GodinaProizvodnje = v.GodinaProizvodnje;
            vm.TipVozilaId = v.TipVozilaId;
            vm.StatusVozilaId = v.StatusVozilaId;
            vm.VrstaGorivaId = v.VrstaGorivaId;
            vm.BrojSjedista = v.BrojSjedista;
            vm.Boja = v.Boja;
            vm.BrojVrata = v.BrojVrata;
            vm.CijenaPoDanu = v.CijenaPoDanu;
            
            return PartialView(vm);
        }

        public IActionResult Obrisi(int id)
        {
            Vozilo x = _context.Vozilo.Find(id);
            _context.Vozilo.Remove(x);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TravelEurope/Areas/AdminPanel/Views/Vozila/Dodaj.cshtml
@using TravelEurope.Areas.AdminPanel.ViewModels
@model TravelEurope.Areas.AdminPanel.ViewModels.VozilaDodajVM
@{
    ViewData["Title"] = "TravelEurope";
    Layout = "AdminPanelLayout";
}
<h2>Dodajte novo vozilo</h2>
<form asp-action="Dodaj" method="post">
    <input type="hidden" value="@Model.VoziloId" name="VoziloId" />
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Naziv">Naziv</label>
        <input asp-for="@Model.Naziv" class="form-control" type="text" />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Tip vozila")
        @Html.DropDownListFor(model => model.TipVozilaId, Model.TipVozilaLista, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.GodinaProizvodnje">Godina proizvodnje</label>
        @Html.DropDownListFor(m => m.GodinaProizvodnje, Enumerable.Range(DateTime.Today.Year - 5, 6).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Marka vozila")
        @Html.DropDownListFor(model => model.MarkaVozilaId, Model.MarkaVozilaLista, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Status vozila")
        @Html.DropDownListFor(model => model.StatusVozilaId, Model.StatusVozilaLista, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Vrsta goriva")
        @Html.DropDownListFor(model => model.VrstaGorivaId, Model.VrstaGorivaLista, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Boja">Boja</label>
        <input asp-for="@Model.Boja" class="form-control" type="text" />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.BrojSjedista">Broj sjedišta</label>
        @Html.DropDownListFor(m => m.BrojSjedista, Enumerable.Range(2, 9).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.BrojVrata">Broj vrata</label>
        @Html.DropDownListFor(m => m.BrojVrata, Enumerable.Range(2, 6).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.CijenaPoDanu">Cijena po danu</label>
        <input asp-for="@Model.CijenaPoDanu" class="form-control" type="number" />
    </div>
    <button type="submit" class="btn btn-success">Sačuvaj</button>
</form>

TravelEurope/Areas/AdminPanel/Views/Vozila/Index.cshtml
@using TravelEurope.Areas.AdminPanel.ViewModels
@model TravelEurope.Areas.AdminPanel.ViewModels.VozilaIndexVM
@{
    ViewData["Title"] = "TravelEurope";
    Layout = "AdminPanelLayout";
}
<h2>Lista trenutnih vozila u ponudi</h2>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Trenutna vozila
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" cellspacing="0">
                <thead>
                    <tr>
                        <th>Naziv</th>
                        <th>Marka vozila</th>
                        <th>Godina proizvodnje</th>
                        <th>Tip vozila</th>
                        <th>Status vozila</th>
                        <th>Vrsta goriva</th>
                        <th>Broj sjedista</th>
                        <th>Boja</th>
                        <th>Broj vrata</th>
                        <th>Cijena usluge po danu</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in Model.Rows)
                    {
                    <tr>
                        <td>@x.Naziv</td>
                        <td>@x.MarkaVozila</td>
                        <td>@x.GodinaProizvodnje.ToString()</td>
                        <td>@x.TipVozila</td>
                        <td>@x.StatusVozila.ToString()</td>
                        <td>@x.VrstaGoriva</td>
                        <td>@x.BrojSjedista</td>
                        <td>@x.Boja</td>
                        <td>@x.BrojVrata</td>
                        <td>@x.CijenaPoDanu KM</td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

TravelEurope/Areas/AdminPanel/Views/Vozila/Uredi.cshtml
@using TravelEurope.Areas.AdminPanel.ViewModels
@model TravelEurope.Areas.AdminPanel.ViewModels.VozilaDodajVM
@{
    ViewData["Title"] = "TravelEurope";
    Layout = "AdminPanelLayout";
}
<h2>Uredite vozilo</h2>
<form asp-area="AdminPanel" asp-controller="Vozila" asp-action="Dodaj">
    <input type="hidden" value="@Model.VoziloId" name="VoziloId" />
    <div class="col-md-4 col-sm-12 form-group">
        <label>Naziv: </label>
        <input asp-for="@Model.Naziv" class="form-control" type="text" />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Tip vozila")
        @Html.DropDownListFor(model => model.TipVozilaId, Model.TipVozilaLista, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.GodinaProizvodnje">Godina proizvodnje</label>
        @Html.DropDownListFor(m => m.GodinaProizvodnje, Enumerable.Range(DateTime.Today.Year - 5, 6).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Marka vozila")
        @Html.DropDownListFor(model => model.MarkaVozilaId, Model.MarkaVozilaLista, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Status vozila")
        @Html.DropDownListFor(model => model.StatusVozilaId, Model.StatusVozilaLista, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Vrsta goriva")
        @Html.DropDownListFor(model => model.VrstaGorivaId, Model.VrstaGorivaLista, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label>Boja: </label>
        <input asp-for="@Model.Boja" class="form-control" type="text" />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.BrojSjedista">Broj sjedišta</label>
        @Html.DropDownListFor(m => m.BrojSjedista, Enumerable.Range(2, 9).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.BrojVrata">Broj vrata</label>
        @Html.DropDownListFor(m => m.BrojVrata, Enumerable.Range(2, 6).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.CijenaPoDanu">Cijena po danu</label>
        <input asp-for="@Model.CijenaPoDanu" class="form-control" type="number" />
    </div>
    <button type="submit" class="btn btn-success">Sačuvaj</button>
</form>