TravelEurope/Areas/AdminPanel/Controllers/RadniciController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TravelEurope.ViewModels;
using TravelEurope.Data;
using TravelEurope.Models;
using Microsoft.AspNetCore.Hosting;
using TravelEurope.Util;
using Microsoft.AspNetCore.Identity;
using TravelEurope.Util.FileManager;
using System.Collections.Generic;
using TravelEurope.Areas.AdminPanel.ViewModels;
using Microsoft.EntityFrameworkCore;
using static TravelEurope.Areas.AdminPanel.ViewModels.RadniciIndexVM;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace TravelEurope.Areas.AdminPanel.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Area("AdminPanel")]
    public class RadniciController : Controller
    {
        private readonly IHostingEnvironment hosting;
        private ApplicationDbContext _db;
        private ImgUploadHelper _imgHelper;
        private UserManagementHelper _userManagementHelper;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RadniciController(ApplicationDbContext db, IHostingEnvironment environment, IFileManager manager, UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            hosting = environment;
            _imgHelper = new ImgUploadHelper(hosting, manager);
            _userManagementHelper = new UserManagementHelper(_db);
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var vm = new RadniciIndexVM() { Rows = new List<Row>() };
            var radnici = _db.Radnik.Include(a => a.ApplicationUser).ToList();

            foreach (var x in radnici)
            {
                var radnik = new Row();
                radnik.KorisnikId = x.ApplicationUser.Id;
                radnik.ImePrezime = x.ApplicationUser.Ime + " " + x.ApplicationUser.Prezime;
                radnik.JMBG = x.ApplicationUser.JMBG;
                radnik.Adresa = x.ApplicationUser.Adresa;
                radnik.Email = x.ApplicationUser.Email;
                radnik.Telefon = x.ApplicationUser.Telefon;
                radnik.Grad = _db.Grad.Where(c => c.GradId == x.ApplicationUser.GradId).SingleOrDefault().Naziv;
                radnik.Pozicija = _db.Radnik.Where(a => a.ApplicationUser.Id == x.RadnikId).FirstOrDefault().Pozicija;
                radnik.GodineStaza = _db.Radnik.Where(a => a.ApplicationUser.Id == x.RadnikId).FirstOrDefault().GodineStaza;
                vm.Rows.Add(radnik);
            };
            return PartialView(vm);
        }

        public IActionResult Obrisi(string id)
        {
            Radnik r = _db.Radnik.Where(x => x.RadnikId == id).FirstOrDefault();

            if (r != null)
            {
                _db.Radnik.Remove(r);
                var userForRemove = _db.Users.FirstOrDefault(x => x.Id == id);
                _db.Users.Remove(userForRemove);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Dodaj()
        {
            KorisniciVM model = _userManagementHelper.prepRadnika();
            return PartialView("Dodaj", model);
        }

        [HttpPost]
        public async Task<IActionResult> Dodaj(KorisniciVM model)
        {
            bool x = await _roleManager.RoleExistsAsync("Radnik");

            if (!x)
            {
                await _roleManager.CreateAsync(new IdentityRole
                {
                    Name = "Radnik"
                });
            }

            //password must be strong enough in order for userManager.CreateAsync to work!!!
            string password = "myP@ssW0r@d123";

            ApplicationUser user = new ApplicationUser
            {
                JMBG = model.JMBG,
                Ime = model.Ime,
                Prezime = model.Prezime,
                DatumRodjenja = model.DatumRodjenja,
                Telefon = model.Telefon,
                Spol = model.Spol,
                Adresa = model.Adresa,
                GradId = model.GradId,
                UserName = model.Ime.ToLower() + '.' + model.Prezime.ToLower(),
                Email = model.Ime + "." + model.Prezime + "@traveleurope.ba"
            };

            await _userManager.CreateAsync(user, password);

            await _userManager.AddToRoleAsync(user, "Radnik");

            Radnik radnik = new Radnik
            {
                RadnikId = user.Id,
                GodineStaza = model.GodineStaza,
                Pozicija = model.Pozicija
            };

            _db.Add(radnik);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Detalji(string id)
        {
            RadniciDetaljiVM vm = new RadniciDetaljiVM();
            vm.Radnik = _db.Radnik.Include(a => a.ApplicationUser).Where(x => x.RadnikId == id).FirstOrDefault();
            return View(vm);
        }

        public IActionResult Uredi(string id)
        {
            Radnik model = _db.Radnik.Include(a => a.ApplicationUser).Where(x => x.RadnikId == id).FirstOrDefault();

            RadniciDodajVM user = new RadniciDodajVM();
            user.Radnik = model;
            user.Radnik.RadnikId = model.RadnikId;
            user.Radnik.ApplicationUser.JMBG = model.ApplicationUser.JMBG;
            user.Radnik.ApplicationUser.Ime = model.ApplicationUser.Ime;
            user.Radnik.ApplicationUser.Prezime = model.ApplicationUser.Prezime;
            user.Radnik.ApplicationUser.DatumRodjenja = model.ApplicationUser.DatumRodjenja;
            user.Radnik.ApplicationUser.Telefon = model.ApplicationUser.Telefon;
            user.Radnik.ApplicationUser.Spol = model.ApplicationUser.Spol;
            user.Radnik.ApplicationUser.Adresa = model.ApplicationUser.Adresa;
            user.Radnik.ApplicationUser.GradId = model.ApplicationUser.GradId;
            user.Radnik.ApplicationUser.UserName = model.ApplicationUser.Ime.ToLower() + '.' + model.ApplicationUser.Prezime.ToLower();
            user.Radnik.ApplicationUser.Email = model.ApplicationUser.Ime + "." + model.ApplicationUser.Prezime + "@traveleurope.ba";
            user.Radnik.GodineStaza = model.GodineStaza;
            user.Radnik.Pozicija = model.Pozicija;

            user.Gradovi = _db.Grad.Include(x => x.Drzava).Select(x => new SelectListItem()
            {
                Value = x.GradId.ToString(),
                Text = x.Naziv + ", " + x.Drzava.Naziv
            }).ToList();
            return PartialView(user);
        }

        [HttpPost]
        public IActionResult UrediSave(RadniciDodajVM model)
        {
            ApplicationUser user = new ApplicationUser();

            Radnik radnik = _db.Radnik.Where(a => a.RadnikId == model.Radnik.RadnikId).Include(b => b.ApplicationUser).SingleOrDefault();

            user = radnik.ApplicationUser;
            user.JMBG = model.Radnik.ApplicationUser.JMBG;
            user.Ime = model.Radnik.ApplicationUser.Ime;
            user.Prezime = model.Radnik.ApplicationUser.Prezime;
            user.DatumRodjenja = model.Radnik.ApplicationUser.DatumRodjenja;
            user.Telefon = model.Radnik.ApplicationUser.Telefon;
            user.Spol = model.Radnik.ApplicationUser.Spol;
            user.Adresa = model.Radnik.ApplicationUser.Adresa;
            user.GradId = model.Radnik.ApplicationUser.GradId;
            user.UserName = model.Radnik.ApplicationUser.Ime.ToLower() + '.' + model.Radnik.ApplicationUser.Prezime.ToLower();
            user.Email = model.Radnik.ApplicationUser.Ime + "." + model.Radnik.ApplicationUser.Prezime + "@traveleurope.ba";

            radnik.GodineStaza = model.Radnik.GodineStaza;
            radnik.Pozicija = model.Radnik.Pozicija;

            _db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

TravelEurope/Areas/RadnikPanel/Controllers/RadniciController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TravelEurope.ViewModels;
using TravelEurope.Data;
using TravelEurope.Models;
using Microsoft.AspNetCore.Hosting;
using TravelEurope.Util;
using Microsoft.AspNetCore.Identity;
using TravelEurope.Util.FileManager;
using System.Collections.Generic;
using TravelEurope.Areas.RadnikPanel.ViewModels;
using Microsoft.EntityFrameworkCore;
using static TravelEurope.Areas.RadnikPanel.ViewModels.RadniciIndexVM;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace TravelEurope.Areas.RadnikPanel.Controllers
{
    [Authorize(Roles = "Radnik")]
    [Area("RadnikPanel")]
    public class RadniciController : Controller
    {
        private readonly IHostingEnvironment hosting;
        private ApplicationDbContext _db;
        private ImgUploadHelper _imgHelper;
        private UserManagementHelper _userManagementHelper;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RadniciController(ApplicationDbContext db, IHostingEnvironment environment, IFileManager manager, UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            hosting = environment;
            _imgHelper = new ImgUploadHelper(hosting, manager);
            _userManagementHelper = new UserManagementHelper(_db);
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var vm = new RadniciIndexVM() { Rows = new List<Row>() };
            var radnici = _db.Radnik.Include(a => a.ApplicationUser).ToList();

            foreach (var x in radnici)
            {
                var radnik = new Row();
                radnik.KorisnikId = x.ApplicationUser.Id;
                radnik.ImePrezime = x.ApplicationUser.Ime + " " + x.ApplicationUser.Prezime;
                radnik.JMBG = x.ApplicationUser.JMBG;
                radnik.Adresa = x.ApplicationUser.Adresa;
                radnik.Email = x.ApplicationUser.Email;
                radnik.Telefon = x.ApplicationUser.Telefon;
                radnik.Grad = _db.Grad.Where(c => c.GradId == x.ApplicationUser.GradId).SingleOrDefault().Naziv;
                radnik.Pozicija = _db.Radnik.Where(a => a.ApplicationUser.Id == x.RadnikId).FirstOrDefault().Pozicija;
                radnik.GodineStaza = _db.Radnik.Where(a => a.ApplicationUser.Id == x.RadnikId).FirstOrDefault().GodineStaza;
                vm.Rows.Add(radnik);
            };
            return View(vm);
        }

        public IActionResult Obrisi(string id)
        {
            Radnik r = _db.Radnik.Where(x => x.RadnikId == id).FirstOrDefault();

            if (r != null)
            {
                _db.Radnik.Remove(r);
                var userForRemove = _db.Users.FirstOrDefault(x => x.Id == id);
                _db.Users.Remove(userForRemove);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Dodaj()
        {
            KorisniciVM model = _userManagementHelper.prepRadnika();
            return View("Dodaj", model);
        }

        [HttpPost]
        public async Task<IActionResult> Dodaj(KorisniciVM model)
        {
            bool x = await _roleManager.RoleExistsAsync("Radnik");

            if (!x)
            {
                await _roleManager.CreateAsync(new IdentityRole
                {
                    Name = "Radnik"
                });
            }

            //password must be strong enough in order for userManager.CreateAsync to work!!!
            string password = "myP@ssW0r@d123";

            ApplicationUser user = new ApplicationUser
            {
                JMBG = model.JMBG,
                Ime = model.Ime,
                Prezime = model.Prezime,
                DatumRodjenja = model.DatumRodjenja,
                Telefon = model.Telefon,
                Spol = model.Spol,
                Adresa = model.Adresa,
                GradId = model.GradId,
                UserName = model.Ime.ToLower() + '.' + model.Prezime.ToLower(),
                Email = model.Ime + "." + model.Prezime + "@traveleurope.ba"
            };

            await _userManager.CreateAsync(user, password);

            await _userManager.AddToRoleAsync(user, "Radnik");

            Radnik radnik = new Radnik
            {
                RadnikId = user.Id,
                GodineStaza = model.GodineStaza,
                Pozicija = model.Pozicija
            };

            _db.Add(radnik);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Detalji(string id)
        {
            RadniciDetaljiVM vm = new RadniciDetaljiVM();
            vm.Radnik = _db.Radnik.Include(a => a.ApplicationUser).Where(x => x.RadnikId == id).FirstOrDefault();
            return View(vm);
        }

        public IActionResult Uredi(string id)
        {
            Radnik model = _db.Radnik.Include(a => a.ApplicationUser).Where(x => x.RadnikId == id).FirstOrDefault();

            RadniciDodajVM user = new RadniciDodajVM();
            user.Radnik = model;
            user.Radnik.RadnikId = model.RadnikId;
            user.Radnik.ApplicationUser.JMBG = model.ApplicationUser.JMBG;
            user.Radnik.ApplicationUser.Ime = model.ApplicationUser.Ime;
            user.Radnik.ApplicationUser.Prezime = model.ApplicationUser.Prezime;
            user.Radnik.ApplicationUser.DatumRodjenja = model.ApplicationUser.DatumRodjenja;
            user.Radnik.ApplicationUser.Telefon = model.ApplicationUser.Telefon;
            user.Radnik.ApplicationUser.Spol = model.ApplicationUser.Spol;
            user.Radnik.ApplicationUser.Adresa = model.ApplicationUser.Adresa;
            user.Radnik.ApplicationUser.GradId = model.ApplicationUser.GradId;
            user.Radnik.ApplicationUser.UserName = model.ApplicationUser.Ime.ToLower() + '.' + model.ApplicationUser.Prezime.ToLower();
            user.Radnik.ApplicationUser.Email = model.ApplicationUser.Ime + "." + model.ApplicationUser.Prezime + "@traveleurope.ba";
            user.Radnik.GodineStaza = model.GodineStaza;
            user.Radnik.Pozicija = model.Pozicija;

            user.Gradovi = _db.Grad.Include(x => x.Drzava).Select(x => new SelectListItem()
            {
                Value = x.GradId.ToString(),
                Text = x.Naziv + ", " + x.Drzava.Naziv
            }).ToList();
            return View(user);
        }

        [HttpPost]
        public IActionResult UrediSave(RadniciDodajVM model)
        {
            ApplicationUser user = new ApplicationUser();

            Radnik radnik = _db.Radnik.Where(a => a.RadnikId == model.Radnik.RadnikId).Include(b => b.ApplicationUser).SingleOrDefault();

            user = radnik.ApplicationUser;
            user.JMBG = model.Radnik.ApplicationUser.JMBG;
            user.Ime = model.Radnik.ApplicationUser.Ime;
            user.Prezime = model.Radnik.ApplicationUser.Prezime;
            user.DatumRodjenja = model.Radnik.ApplicationUser.DatumRodjenja;
            user.Telefon = model.Radnik.ApplicationUser.Telefon;
            user.Spol = model.Radnik.ApplicationUser.Spol;
            user.Adresa = model.Radnik.ApplicationUser.Adresa;
            user.GradId = model.Radnik.ApplicationUser.GradId;
            user.UserName = model.Radnik.ApplicationUser.Ime.ToLower() + '.' + model.Radnik.ApplicationUser.Prezime.ToLower();
            user.Email = model.Radnik.ApplicationUser.Ime + "." + model.Radnik.ApplicationUser.Prezime + "@traveleurope.ba";

            radnik.GodineStaza = model.Radnik.GodineStaza;
            radnik.Pozicija = model.Radnik.Pozicija;

            _db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

TravelEurope/Areas/RadnikPanel/Views/Radnici/Detalji.cshtml
@model TravelEurope.Areas.RadnikPanel.ViewModels.RadniciDetaljiVM
@{
    Layout = "RadnikPanelLayout";

}
<div class="form-group">
    <div class="row">
        <label asp-for="@Model.Radnik.RadnikId"></label>
        <input asp-for="@Model.Radnik.RadnikId" hidden />
    </div>
    <div class="col">
        <label asp-for="@Model.Radnik.ApplicationUser.Ime">Ime </label>
        <input asp-for="@Model.Radnik.ApplicationUser.Ime" class="form-control col-6 col-sm-6" disabled>
    </div>
    <div class="col">
        <label asp-for="@Model.Radnik.ApplicationUser.Prezime">Prezime </label>
        <textarea asp-for="@Model.Radnik.ApplicationUser.Prezime" class="form-control col-6 col-sm-6"></textarea>
    </div>
    <div class="col">
        <label asp-for="@Model.Radnik.ApplicationUser.JMBG">JMBG </label>
        <textarea asp-for="@Model.Radnik.ApplicationUser.JMBG" class="form-control col-6 col-sm-6"></textarea>
    </div>
    <div class="col">
        <label asp-for="@Model.Radnik.ApplicationUser.Adresa">Adresa </label>
        <textarea asp-for="@Model.Radnik.ApplicationUser.Adresa" class="form-control col-6 col-sm-6"></textarea>
    </div>
    <div class="col">
        <label asp-for="@Model.Radnik.ApplicationUser.Telefon">Telefon </label>
        <textarea asp-for="@Model.Radnik.ApplicationUser.Telefon" class="form-control col-6 col-sm-6"></textarea>
    </div>
    <div class="col">
        <label asp-for="@Model.Radnik.ApplicationUser.Grad">Grad </label>
        <textarea asp-for="@Model.Radnik.ApplicationUser.Grad" class="form-control col-6 col-sm-6"></textarea>
    </div>
    <div class="col">
        <label asp-for="@Model.Radnik.GodineStaza">Godine staza </label>
        <textarea asp-for="@Model.Radnik.GodineStaza" class="form-control col-6 col-sm-6"></textarea>
    </div>
    <div class="col">
        <label asp-for="@Model.Radnik.Pozicija">Pozicija </label>
        <textarea asp-for="@Model.Radnik.Pozicija" class="form-control col-6 col-sm-6"></textarea>
    </div>
</div>

TravelEurope/Areas/RadnikPanel/Views/Radnici/Dodaj.cshtml
@model TravelEurope.ViewModels.KorisniciVM
@{
    Layout = "RadnikPanelLayout";

}
<h2>Dodajte novog radnika</h2>

<form asp-controller="Radnici" asp-action="Dodaj" method="post">
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.JMBG">JMBG</label>
        <input name="JMBG" asp-for="@Model.JMBG" class="form-control  col-md-12" type="text" placeholder="Unesite JMBG radnika" autocomplete="off" required />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Ime">Ime</label>
        <input name="Ime" asp-for="@Model.Ime" class="form-control  col-md-12" type="text" placeholder="Unesite ime" min="2" max="20" autocomplete="off" required />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Prezime">Prezime</label>
        <input name="Prezime" asp-for="@Model.Prezime" class="form-control  col-md-12" type="text" placeholder="Unesite prezime" min="2" max="20" autocomplete="off" required />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.DatumRodjenja">Datum rođenja</label>
        <input name="DatumRodjenja" asp-for="@Model.DatumRodjenja" class="form-control  col-md-12" type="date" required />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Telefon">Telefon</label>
        <input name="Telefon" asp-for="@Model.Telefon" type="text" class="form-control col-md-12" placeholder="Unesite broj telefona" autocomplete="off" required />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Spol">Spol</label>
        @Html.DropDownListFor(model => model.Spol, Model.Spolovi, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Adresa">Adresa</label>
        <input name="Adresa" asp-for="@Model.Adresa" type="text" class="form-control col-md-12" placeholder="Unesite adresu" autocomplete="off" required />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.GradId">Grad</label>
        @Html.DropDownListFor(model => model.GradId, Model.Gradovi, new { @class = "form-control" })
    </div>
    <div class="col-md-4 form-group">
        <label>Pozicija:</label>
        <input name="Pozicija" asp-for="@Model.Pozicija" type="text" class="form-control col-md-12" placeholder="Unesite poziciju" autocomplete="off" />
    </div>
    <div class="col-md-4 form-group">
        <label asp-for="@Model.GodineStaza">Godine staža:</label>
        <input name="GodineStaza"  type="number" asp-for="@Model.GodineStaza" class="form-control" autocomplete="off" />
    </div>
    <div class="row">
        <div class="col-md-2 col-sm-12" style="margin-bottom: 1em;">
            <input type="submit" class="btn btn-danger col-md-12 " value="Spremi" />
        </div>
    </div>

</form>

TravelEurope/Areas/RadnikPanel/Views/Radnici/Index.cshtml
@model TravelEurope.Areas.RadnikPanel.ViewModels.RadniciIndexVM
@{
    Layout = "RadnikPanelLayout";

}
<h2>Lista trenutno zaposlenih radnika</h2>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Trenutno zaposleni
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Ime i prezime</th>
                        <th>JMBG</th>
                        <th>Adresa</th>
                        <th>Telefon</th>
                        <th>Grad</th>
                        <th>Godine staža</th>
                        <th>Pozicija</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in Model.Rows)
                    {
                        <tr>
                            <td>@x.ImePrezime</td>
                            <td>@x.JMBG</td>
                            <td>@x.Adresa</td>
                            <td>@x.Telefon</td>
                            <td>@x.Grad</td>
                            <td>@x.GodineStaza</td>
                            <td>@x.Pozicija</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

TravelEurope/Areas/RadnikPanel/Views/Radnici/Uredi.cshtml
@model TravelEurope.Areas.RadnikPanel.ViewModels.RadniciDodajVM
@{
    Layout = "RadnikPanelLayout";

}
<form asp-area="RadnikPanel" asp-controller="Radnici" asp-action="UrediSave">
    <div class="form-group">
        @Html.HiddenFor(x => x.Radnik.RadnikId)
        <div class="row">
            <div class="col-3 col-sm-3">
                @Html.HiddenFor(x => x.Radnik.RadnikId)
            </div>
        </div>
        <div class="row">
            <div class="col-3 col-sm-3">
                <label asp-for="@Model.Radnik.ApplicationUser.Ime">Ime </label><br />
                <input asp-for="@Model.Radnik.ApplicationUser.Ime" class="form-control">
            </div>
        </div>

        <div class="row">
            <div class="col-3 col-sm-3">
                <label asp-for="@Model.Radnik.ApplicationUser.Prezime">Prezime </label>
                <input asp-for="@Model.Radnik.ApplicationUser.Prezime" class="form-control">
            </div>
        </div>

        <div class="row">
            <div class="col-3 col-sm-3">
                <label asp-for="@Model.Radnik.ApplicationUser.JMBG">JMBG </label>
                <input asp-for="@Model.Radnik.ApplicationUser.JMBG" class="form-control">
            </div>
        </div>

        <div class="row">
            <div class="col-3 col-sm-3">
                <label asp-for="@Model.Radnik.ApplicationUser.Adresa">Adresa </label>
                <input asp-for="@Model.Radnik.ApplicationUser.Adresa" class="form-control">
            </div>
        </div>

        <div class="row">
            <div class="col-3 col-sm-3">
                <label asp-for="@Model.Radnik.ApplicationUser.Telefon">Telefon </label>
                <input asp-for="@Model.Radnik.ApplicationUser.Telefon" class="form-control">
            </div>
        </div>

        <div class="row">
            <div class="col-3 col-sm-3">
                <label asp-for="@Model.Radnik.ApplicationUser.GradId">Grad </label>
                <select asp-for="@Model.Radnik.ApplicationUser.GradId" asp-items="@Model.Gradovi" class="form-control"></select>
            </div>
        </div>

        <div class="row">
            <div class="col-3 col-sm-3">
                <label asp-for="@Model.Radnik.GodineStaza">Godine staza </label>
                <input asp-for="@Model.Radnik.GodineStaza" class="form-control">
            </div>
        </div>

        <div class="row">
            <div class="col-3 col-sm-3">
                <label asp-for="@Model.Radnik.Pozicija">Pozicija </label>
                <input asp-for="@Model.Radnik.Pozicija" class="form-control">
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="row">
                <div class="col-12 col-sm-12">
                    <div class="col-12 col-sm-12 text-left">
                        <button class="btn btn-outline-success">Snimi</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>