TravelEurope/Areas/AdminPanel/Controllers/TuristRuteController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TravelEurope.Areas.AdminPanel.ViewModels;
using TravelEurope.Data;
using TravelEurope.Models;

namespace TravelEurope.Controllers
{
    [Authorize(Roles = "Administrator")]
    [Area("AdminPanel")]
    public class TuristRuteController : Controller
    {
        private ApplicationDbContext _context;

        public TuristRuteController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            TuristRuteIndexVM vm = new TuristRuteIndexVM()
            {
                Rows = _context.TuristRuta.Select(x => new TuristRuteIndexVM.Row()
                {
                    TuristRutaId = x.TuristRutaId,
                    Naziv = x.Naziv,
                    Opis = x.Opis,
                    TuristickiVodic = x.TuristickiVodic.Ime + " " + x.TuristickiVodic.Prezime,
                    Drzava = x.Drzava.Naziv,
                    CijenaPoDanu = x.CijenaPoDanu
                }).ToList()
            };
            return View(vm);
        }
    }
}

TravelEurope/Areas/RadnikPanel/Controllers/TuristRuteController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TravelEurope.Areas.RadnikPanel.ViewModels;
using TravelEurope.Data;
using TravelEurope.Models;

namespace TravelEurope.Areas.RadnikPanel.Controllers
{
    [Authorize(Roles = "Radnik")]
    [Area("RadnikPanel")]
    public class TuristRuteController : Controller
    {
        private ApplicationDbContext _context;

        public TuristRuteController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            TuristRuteIndexVM vm = new TuristRuteIndexVM()
            {
                Rows = _context.TuristRuta.Select(x => new TuristRuteIndexVM.Row()
                {
                    TuristRutaId = x.TuristRutaId,
                    Naziv = x.Naziv,
                    Opis = x.Opis,
                    TuristickiVodic = x.TuristickiVodic.Ime + " " + x.TuristickiVodic.Prezime,
                    Drzava = x.Drzava.Naziv,
                    CijenaPoDanu = x.CijenaPoDanu
                }).ToList()
            };
            return View(vm);
        }

        public IActionResult Dodaj()
        {
            TuristRuteDodajVM vm = new TuristRuteDodajVM()
            {
                DrzaveList = _context.Drzava.Select(x => new SelectListItem
                {
                    Value = x.DrzavaId.ToString(),
                    Text = x.Naziv
                }).ToList(),
                VodiciList = _context.TuristickiVodic.Select(x => new SelectListItem
                {
                    Value = x.TuristickiVodicId.ToString(),
                    Text = x.Ime + " " + x.Prezime + ", " + x.StraniJezik
                }).ToList()
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult Dodaj(TuristRuteDodajVM vm)
        {
            TuristRuta v = _context.TuristRuta.Where(a => a.TuristRutaId == vm.TuristRutaId).SingleOrDefault();
            if (v == null)
            {
                TuristRuta a = new TuristRuta
                {
                    TuristRutaId = vm.TuristRutaId,
                    Naziv = vm.Naziv,
                    Opis = vm.Opis,
                    DrzavaId = vm.DrzavaId,
                    TuristickiVodicId = vm.TuristickiVodicId,
                    CijenaPoDanu = vm.CijenaPoDanu
                };
                _context.TuristRuta.Add(a);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            v.TuristRutaId = vm.TuristRutaId;
            v.Naziv = vm.Naziv;
            v.Opis = vm.Opis;
            v.DrzavaId = vm.DrzavaId;
            v.TuristickiVodicId = vm.TuristickiVodicId;
            v.CijenaPoDanu = vm.CijenaPoDanu;

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Uredi(int id)
        {
            TuristRuteDodajVM vm = new TuristRuteDodajVM();
            TuristRuta v = _context.TuristRuta.Where(a => a.TuristRutaId == id).SingleOrDefault();

            vm.DrzaveList = _context.Drzava.Select(x => new SelectListItem
            {
                Value = x.DrzavaId.ToString(),
                Text = x.Naziv
            }).ToList();
            vm.VodiciList = _context.TuristickiVodic.Select(x => new SelectListItem
            {
                Value = x.TuristickiVodicId.ToString(),
                Text = x.Ime + " " + x.Prezime + ", " + x.StraniJezik
            }).ToList();


            vm.TuristRutaId = v.TuristRutaId;
            vm.Naziv = v.Naziv;
            vm.Opis = v.Opis;
            vm.DrzavaId = v.DrzavaId;
            vm.TuristickiVodicId = v.TuristickiVodicId;
            vm.CijenaPoDanu = v.CijenaPoDanu;

            return View(vm);
        }

        public IActionResult Obrisi(int id)
        {
            TuristRuta x = _context.TuristRuta.Find(id);
            _context.TuristRuta.Remove(x);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TravelEurope/Areas/RadnikPanel/Views/TuristRute/Dodaj.cshtml
@using TravelEurope.Areas.RadnikPanel.ViewModels
@model TravelEurope.Areas.RadnikPanel.ViewModels.TuristRuteDodajVM
@{
    ViewData["Title"] = "TravelEurope";
    Layout = "RadnikPanelLayout";
}
<h2>Dodajte novu turist rutu</h2>
<form asp-action="Dodaj" method="post">
    <input type="hidden" value="@Model.TuristRutaId" name="VoziloId" />
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Naziv">Naziv</label>
        <input name="Naziv" asp-for="@Model.Naziv" class="form-control" type="text" required />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Opis">Opis</label>
        <input name="Opis" asp-for="@Model.Opis" class="form-control" type="text" required />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Država: ")
        @Html.DropDownListFor(model => model.DrzavaId, Model.DrzaveList, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Izaberite vodiča: ")
        @Html.DropDownListFor(model => model.TuristickiVodicId, Model.VodiciList, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.CijenaPoDanu">Cijena po danu</label>
        <input asp-for="@Model.CijenaPoDanu" class="form-control" type="number" />
    </div>
    <button type="submit" class="btn btn-success">Sačuvaj</button>
</form>

TravelEurope/Areas/RadnikPanel/Views/TuristRute/Index.cshtml
@using TravelEurope.Areas.RadnikPanel.ViewModels
@model TravelEurope.Areas.RadnikPanel.ViewModels.TuristRuteIndexVM
@{
    ViewData["Title"] = "TravelEurope";
    Layout = "RadnikPanelLayout";
}
<h2>Lista svih turist ruta</h2>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Trenutne turist rute
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Naziv</th>
                        <th>Opis</th>
                        <th>Turistički vodič</th>
                        <th>Država</th>
                        <th>Cijena po danu</th>
                        <th>Akcije</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in Model.Rows)
                    {
                    <tr>
                        <td>@x.Naziv</td>
                        <td>@x.Opis</td>
                        <td>@x.TuristickiVodic</td>
                        <td>@x.Drzava</td>
                        <td>@x.CijenaPoDanu KM</td>
                        <td>
                            <a asp-action="Uredi" asp-controller="TuristRute" asp-route-id="@x.TuristRutaId" class="btn btn-info font-sizes"><i class="fas fa-search icons-margin-right"></i> Uredi </a>
                            <a asp-action="Obrisi" asp-controller="TuristRute" asp-route-id="@x.TuristRutaId" class="btn btn-danger font-sizes"><i class="fas fa-delete icons-margin-right"></i> Obriši turist rutu</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<a asp-action="Dodaj" asp-controller="TuristRute" class="btn btn-success  col-md-2 font-sizes"><i class="fas fa-plus-circle icons-margin-right"></i> Dodaj turist rutu</a>

TravelEurope/Areas/RadnikPanel/Views/TuristRute/Uredi.cshtml
@using TravelEurope.Areas.RadnikPanel.ViewModels
@model TravelEurope.Areas.RadnikPanel.ViewModels.TuristRuteDodajVM
@{
    ViewData["Title"] = "TravelEurope";
    Layout = "RadnikPanelLayout";

}
<h2>Uredite turist rutu</h2>
<form asp-area="RadnikPanel" asp-controller="TuristRute" asp-action="Dodaj">
    @Html.HiddenFor(x => x.TuristRutaId)
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Naziv">Naziv</label>
        <input name="Naziv" asp-for="@Model.Naziv" class="form-control" type="text" />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.Opis">Opis</label>
        <input name="Opis" asp-for="@Model.Opis" class="form-control" type="text" required />
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Država: ")
        @Html.DropDownListFor(model => model.DrzavaId, Model.DrzaveList, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        @Html.Label("Izaberite vodiča: ")
        @Html.DropDownListFor(model => model.TuristickiVodicId, Model.VodiciList, new { @class = "form-control" })
    </div>
    <div class="col-md-4 col-sm-12 form-group">
        <label asp-for="@Model.CijenaPoDanu">Cijena po danu</label>
        <input asp-for="@Model.CijenaPoDanu" class="form-control" type="number" />
    </div>
    <button type="submit" class="btn btn-success">Sačuvaj</button>
</form>